ALTER TABLE "store_access_blocks"
  ADD COLUMN IF NOT EXISTS "source" text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS "reason_code" text,
  ADD COLUMN IF NOT EXISTS "subscription_id" integer REFERENCES "store_subscriptions"("id") ON DELETE set null ON UPDATE no action,
  ADD COLUMN IF NOT EXISTS "invoice_id" integer REFERENCES "store_billing_invoices"("id") ON DELETE set null ON UPDATE no action,
  ADD COLUMN IF NOT EXISTS "dedupe_key" text;

DO $$
BEGIN
  ALTER TABLE "store_access_blocks"
    DROP CONSTRAINT IF EXISTS "store_access_blocks_source_check";

  ALTER TABLE "store_access_blocks"
    ADD CONSTRAINT "store_access_blocks_source_check"
    CHECK ("source" IN ('manual', 'billing_delinquency'));

  ALTER TABLE "store_access_blocks"
    DROP CONSTRAINT IF EXISTS "store_access_blocks_billing_shape_check";

  ALTER TABLE "store_access_blocks"
    ADD CONSTRAINT "store_access_blocks_billing_shape_check"
    CHECK (
      "source" <> 'billing_delinquency'
      OR (
        "reason_code" = 'invoice_overdue_after_grace'
        AND "subscription_id" IS NOT NULL
        AND "invoice_id" IS NOT NULL
        AND "dedupe_key" IS NOT NULL
        AND "notify_store_owner" IS TRUE
      )
    );
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "store_access_blocks_dedupe_key_unique"
  ON "store_access_blocks" ("dedupe_key")
  WHERE "dedupe_key" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "store_access_blocks_invoice_idx"
  ON "store_access_blocks" ("invoice_id");

ALTER TABLE "store_subscriptions"
  ADD COLUMN IF NOT EXISTS "billing_access_exemption_kind" text,
  ADD COLUMN IF NOT EXISTS "billing_access_exempt_until" timestamp,
  ADD COLUMN IF NOT EXISTS "billing_access_exemption_reason" text;

DO $$
BEGIN
  ALTER TABLE "store_subscriptions"
    DROP CONSTRAINT IF EXISTS "store_subscriptions_billing_access_exemption_kind_check";

  ALTER TABLE "store_subscriptions"
    ADD CONSTRAINT "store_subscriptions_billing_access_exemption_kind_check"
    CHECK (
      "billing_access_exemption_kind" IS NULL
      OR "billing_access_exemption_kind" IN ('courtesy', 'manual_exception')
    );

  ALTER TABLE "store_subscriptions"
    DROP CONSTRAINT IF EXISTS "store_subscriptions_billing_access_exemption_shape_check";

  ALTER TABLE "store_subscriptions"
    ADD CONSTRAINT "store_subscriptions_billing_access_exemption_shape_check"
    CHECK (
      (
        "billing_access_exemption_kind" IS NULL
        AND "billing_access_exempt_until" IS NULL
        AND "billing_access_exemption_reason" IS NULL
      )
      OR
      (
        "billing_access_exemption_kind" IS NOT NULL
        AND "billing_access_exempt_until" IS NOT NULL
        AND length(trim(coalesce("billing_access_exemption_reason", ''))) >= 8
      )
    );

  ALTER TABLE "store_billing_events"
    DROP CONSTRAINT IF EXISTS "store_billing_events_event_type_check";

  ALTER TABLE "store_billing_events"
    ADD CONSTRAINT "store_billing_events_event_type_check"
    CHECK ("event_type" IN (
      'subscription_created',
      'subscription_changed',
      'subscription_cancelled',
      'invoice_created',
      'invoice_status_changed',
      'payment_registered',
      'payment_confirmed',
      'payment_failed',
      'refund_registered',
      'billing_adjustment_created',
      'billing_reminder_sent',
      'billing_access_blocked'
    ));
END $$;

CREATE INDEX IF NOT EXISTS "store_subscriptions_billing_access_exempt_until_idx"
  ON "store_subscriptions" ("billing_access_exempt_until");

COMMENT ON COLUMN "store_access_blocks"."source" IS
  'Origin of the store access block. Billing delinquency blocks are generated by the protected billing cron.';

COMMENT ON COLUMN "store_access_blocks"."dedupe_key" IS
  'Idempotency key for automatic access blocks, especially one block per delinquent invoice.';

COMMENT ON COLUMN "store_subscriptions"."billing_access_exemption_kind" IS
  'Optional financial exception that prevents automatic delinquency access blocks while active.';

COMMENT ON COLUMN "store_subscriptions"."billing_access_exempt_until" IS
  'Expiration date for the financial access block exemption.';
